### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by ralph27** [ralph27/markdown-portfolio#2]
- [x] Turn on GitHub Pages
- [x] Outline my portfolio
- [ ] Introduce myself to the world
